### ISSUE TITLE
Pages are all just HTML Login page

### ISSUE THREAD

**Issue by intrepidsilence** [homeylab/bookstack-file-exporter#35]
So, we got our Bookstack instance upgraded and the script runs without error. However, while all of the images are downloaded correctly, all of the pages are exactly the same page - an HTML login page. 

I don't understand why it would pull down an HTML login page when it is using the API which is clearly working since the images are downloading correctly.

Config yaml looks like this:
```yaml
host: "https://wiki.redacted.com"
credentials:
    token_id: "<redacted>"
    token_secret: "<redacted>"
formats:
  - markdown
output_path: "/root/Wiki"
assets:
  export_images: true
  modify_markdown: true
  export_meta: false
  verify_ssl: true
  keep_last: 1
```
