### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by balgerion** [homeylab/bookstack-file-exporter#61]
This is only feature that I would love to use/have here that is missing.
It can be really simple like running script after successful run than anyone can implement their own solution (like discord.sh for example) or something more complicated like integration with apprise etc.

**Comment by pchang388** [comment]
Hey @balgerion - thank you again for opening an issue and improving the project. I've been a bit busy with personal life but I will get back to you and take a look and see what we can do for this in a few days!

**Comment by pchang388** [comment]
@balgerion  sorry for the late reply, been on holiday + work but taking a look into this. I see apprise has a python client API, is there any preferences on which notifications systems you prefer as a first iteration? Email, discord, pushover, etc.?

**Comment by balgerion** [comment]
If you implement API for apprise I think all clients will work trough it - apprise act as a forward proxy for notifications but I’m using mainly discord for notification.

**Comment by pchang388** [comment]
Hey @Avago79  - thanks for the input. I believe if I implement apprise as an optional feature, it should cover your use case (https://github.com/caronc/apprise/wiki/Notify_Custom_JSON).

Apprise should take care of most user needs and I don't have to keep implementing features for different notification services or protocols like the OP mentioned.

I have a busy schedule this month but I expect to be able to start working on personal projects like this by the end of this month and should have something for you then. Sorry for the delay!

**Comment by Avago79** [comment]
That sounds like a good solution.
I will follow up on the project, thank you!

**Comment by pchang388** [comment]
Just an update, thanks for the patience! I started working on this and should have something done soon.

**Comment by pchang388** [comment]
This is done, I don't have a lot of experience with apprise but I was able to get simple HTTP notifications sent when an error occurs. `v1.6.0` has the new apprise feature.  Hopefully it works for everyone.

Example configuration:
```yaml
## optional - if specified exporter will send notifications on failure
# supported notification services are:
# - apprise (https://github.com/caronc/apprise)
# omit/comment out section if not required
notifications:
  # optional - apprise notification config
  # if used, required: specify one or more service_urls or a config_path
  # - if both are specified, config_path takes precedence
  # if service_urls is used, service_urls can also be specified as env var: APPRISE_URLS
  # - env var takes precedence over service_urls below if both specified
  apprise:
    service_urls:
      - "json://localhost:8080/notify"
    config_path: ""
    plugin_paths: []
    storage_path: ""
    custom_title: ""
    custom_attachment_path: ""
```

Example uses JSON HTTP POST request for notification (https://github.com/caronc/apprise/wiki/Notify_Custom_JSON).  Feel free to open a new issue if I missed something or doesn't work. Thank you!

**Comment by pchang388** [comment]
I just realized (should have re-read the original post), we also want notifications when a run is successful, I'll go back and add that shortly. Apologies!

**Comment by pchang388** [comment]
I included the notifications on successful runs. I plan on going back and enriching the notification message body with info about the exported file (name, size, etc.) for successful runs. Will do that soon as well.

Example:
```
## optional - if specified exporter will send notifications on failure
# supported notification services are:
# - apprise (https://github.com/caronc/apprise)
# omit/comment out section if not required
notifications:
  # optional - apprise notification config
  # if used, required: specify one or more service_urls or a config_path
  # - if both are specified, config_path takes precedence
  # if service_urls is used, service_urls can also be specified as env var: APPRISE_URLS
  # - env var takes precedence over service_urls below if both specified
  apprise:
    service_urls: []
      # - "json://localhost:8080/notify"
    config_path: ""
    plugin_paths: []
    storage_path: ""
    custom_title: ""
    custom_attachment_path: ""
    on_success: false
    on_failure: true
```

`on_success` and `on_failure` allow you to control when to send a notification. Currently the message title is configurable (`custom_title`). Thanks again!
